// Code generated by Kitex v0.15.4. DO NOT EDIT.

package userservice

import (
	"context"
	v1 "github.com/XDWow/DouyinMall/backend/rpc_gen/kitex_gen/user/v1"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	Register(ctx context.Context, Req *v1.RegisterReq, callOptions ...callopt.Option) (r *v1.RegisterResp, err error)
	Login(ctx context.Context, Req *v1.LoginReq, callOptions ...callopt.Option) (r *v1.LoginResp, err error)
	Logout(ctx context.Context, Req *emptypb.Empty, callOptions ...callopt.Option) (r *emptypb.Empty, err error)
	Update(ctx context.Context, Req *v1.UpdateUserReq, callOptions ...callopt.Option) (r *emptypb.Empty, err error)
	Delete(ctx context.Context, Req *v1.DeleteUserReq, callOptions ...callopt.Option) (r *emptypb.Empty, err error)
	Query(ctx context.Context, Req *v1.QueryUserReq, callOptions ...callopt.Option) (r *v1.QueryUserResp, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kUserServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kUserServiceClient struct {
	*kClient
}

func (p *kUserServiceClient) Register(ctx context.Context, Req *v1.RegisterReq, callOptions ...callopt.Option) (r *v1.RegisterResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Register(ctx, Req)
}

func (p *kUserServiceClient) Login(ctx context.Context, Req *v1.LoginReq, callOptions ...callopt.Option) (r *v1.LoginResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Login(ctx, Req)
}

func (p *kUserServiceClient) Logout(ctx context.Context, Req *emptypb.Empty, callOptions ...callopt.Option) (r *emptypb.Empty, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Logout(ctx, Req)
}

func (p *kUserServiceClient) Update(ctx context.Context, Req *v1.UpdateUserReq, callOptions ...callopt.Option) (r *emptypb.Empty, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Update(ctx, Req)
}

func (p *kUserServiceClient) Delete(ctx context.Context, Req *v1.DeleteUserReq, callOptions ...callopt.Option) (r *emptypb.Empty, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Delete(ctx, Req)
}

func (p *kUserServiceClient) Query(ctx context.Context, Req *v1.QueryUserReq, callOptions ...callopt.Option) (r *v1.QueryUserResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Query(ctx, Req)
}
