// Code generated by Kitex v0.15.4. DO NOT EDIT.

package userv1

import (
	"context"
	"google.golang.org/protobuf/types/known/emptypb"

	"github.com/cloudwego/prutal"
)

type RegisterReq struct {
	Email    string `protobuf:"bytes,1,opt,name=email" json:"email,omitempty"`
	Password string `protobuf:"bytes,2,opt,name=password" json:"password,omitempty"`
}

func (x *RegisterReq) Reset() { *x = RegisterReq{} }

func (x *RegisterReq) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *RegisterReq) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *RegisterReq) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *RegisterReq) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type RegisterResp struct {
	UserId int32 `protobuf:"varint,1,opt,name=user_id" json:"user_id,omitempty"`
}

func (x *RegisterResp) Reset() { *x = RegisterResp{} }

func (x *RegisterResp) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *RegisterResp) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *RegisterResp) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type LoginReq struct {
	Email    string `protobuf:"bytes,1,opt,name=email" json:"email,omitempty"`
	Password string `protobuf:"bytes,2,opt,name=password" json:"password,omitempty"`
}

func (x *LoginReq) Reset() { *x = LoginReq{} }

func (x *LoginReq) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *LoginReq) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *LoginReq) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *LoginReq) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type LoginResp struct {
	UserId   int64  `protobuf:"varint,1,opt,name=user_id" json:"user_id,omitempty"`
	Username string `protobuf:"bytes,2,opt,name=username" json:"username,omitempty"`
	Email    string `protobuf:"bytes,3,opt,name=email" json:"email,omitempty"`
}

func (x *LoginResp) Reset() { *x = LoginResp{} }

func (x *LoginResp) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *LoginResp) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *LoginResp) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *LoginResp) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *LoginResp) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type UpdateUserReq struct {
	UserId   int64   `protobuf:"varint,1,opt,name=user_id" json:"user_id,omitempty"`
	Username *string `protobuf:"bytes,2,opt,name=username" json:"username,omitempty"`
	Avatar   *string `protobuf:"bytes,3,opt,name=avatar" json:"avatar,omitempty"`
	Email    *string `protobuf:"bytes,4,opt,name=email" json:"email,omitempty"`
}

func (x *UpdateUserReq) Reset() { *x = UpdateUserReq{} }

func (x *UpdateUserReq) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *UpdateUserReq) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *UpdateUserReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UpdateUserReq) GetUsername() string {
	if x != nil && x.Username != nil {
		return *x.Username
	}
	return ""
}

func (x *UpdateUserReq) GetAvatar() string {
	if x != nil && x.Avatar != nil {
		return *x.Avatar
	}
	return ""
}

func (x *UpdateUserReq) GetEmail() string {
	if x != nil && x.Email != nil {
		return *x.Email
	}
	return ""
}

type DeleteUserReq struct {
	UserId int64 `protobuf:"varint,1,opt,name=user_id" json:"user_id,omitempty"`
}

func (x *DeleteUserReq) Reset() { *x = DeleteUserReq{} }

func (x *DeleteUserReq) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *DeleteUserReq) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *DeleteUserReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type QueryUserReq struct {
	UserId int64 `protobuf:"varint,1,opt,name=user_id" json:"user_id,omitempty"`
}

func (x *QueryUserReq) Reset() { *x = QueryUserReq{} }

func (x *QueryUserReq) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *QueryUserReq) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *QueryUserReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type QueryUserResp struct {
	User *User `protobuf:"bytes,1,opt,name=user" json:"user,omitempty"`
}

func (x *QueryUserResp) Reset() { *x = QueryUserResp{} }

func (x *QueryUserResp) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *QueryUserResp) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *QueryUserResp) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

type User struct {
	UserId   int64  `protobuf:"varint,1,opt,name=user_id" json:"user_id,omitempty"`
	Email    string `protobuf:"bytes,2,opt,name=email" json:"email,omitempty"`
	Username string `protobuf:"bytes,3,opt,name=username" json:"username,omitempty"`
	Avatar   string `protobuf:"bytes,4,opt,name=avatar" json:"avatar,omitempty"`
}

func (x *User) Reset() { *x = User{} }

func (x *User) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *User) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *User) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *User) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *User) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *User) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

type UserService interface {
	Register(ctx context.Context, req *RegisterReq) (res *RegisterResp, err error)
	Login(ctx context.Context, req *LoginReq) (res *LoginResp, err error)
	Logout(ctx context.Context, req *emptypb.Empty) (res *emptypb.Empty, err error)
	Update(ctx context.Context, req *UpdateUserReq) (res *emptypb.Empty, err error)
	Delete(ctx context.Context, req *DeleteUserReq) (res *emptypb.Empty, err error)
	Query(ctx context.Context, req *QueryUserReq) (res *QueryUserResp, err error)
}
